sudo: required 
services:
    - dockerfile

before_install:
    - docker build -t dockeryoutube -f Dockerfile.dev .

scripts:
    - docker run -e CI=true dockeryoutube npm run test      



deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: &3
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "docker-youtube"
  env: "DockerYoutube-env"
  bucket: code-deploy-builds
  
  on:
      all_branches: true
