sudo: required 
services:
    - docker

before_install:
    - docker build -t muzafardba/dockeryoutube -f Dockerfile.dev .

script:
    - docker run -e CI=true muzafardba/dockeryoutube npm run test      

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push muzafardba/dockeryoutube
