sudo: required 
services:
    - docker

before_install:
    - docker build -t muzafardba/dockeryoutube -f Dockerfile.dev .

script:
    - docker run -e CI=true muzafardba/dockeryoutube npm run test      

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push muzafardba/dockeryoutube
  
 deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "test-you-tube"
  env: "TestYouTube-env"
  bucket_name: "elasticbeanstalk-us-east-2-251636963513"
  bucket_path: "test-you-tube"
  on:
      branch: master
 
