sudo: required 
services:
    - dockerfile

before_install:
    - docker build -t dockeryoutube -f Dockerfile.dev .

scripts:
    - docker run -e CI=true dockeryoutube npm run test      



deploy:
  provider: s3
    
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: "$AWS_SECRET_ACCESS_KEY"
  
  region: "us-east-2"
  app: "docker-youtube"
  env: "DockerYoutube-env"
  bucket_name: "elasticbeanstalk-us-east-2-251636963513"
  bucket_path: "docker-youtube-docker"
  on:
    branch: main
    
